9AspNetCoreWebAppMVC/9AspNetCoreWebAppMVC/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _9AspNetCoreWebAppMVC.Data;
using _9AspNetCoreWebAppMVC.Models;
using _9AspNetCoreWebAppMVC.Data.Services;

namespace _9AspNetCoreWebAppMVC.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICoursesService _service;

        public CoursesController(ICoursesService service)
        {
            _service = service;
        }

        // GET: Courses
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAll();
            return View(data);
        }
        
        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var courseDetails = await _service.GetById(id);
            if (courseDetails == null)
            {
                return View("NotFound");
            }
            return View(courseDetails);
        }

        // GET: Courses/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Courses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Description")] Course course)
        {
            if (!ModelState.IsValid)
            {
                return View(course);
            }
            await _service.Add(course);
            return RedirectToAction(nameof(Index));
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var courseDetails = await _service.GetById(id);
            if (courseDetails == null)
            {
                return View("NotFound");
            }
            return View(courseDetails);
        }

        // POST: Courses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Course course)
        {
            if (!ModelState.IsValid)
            {
                return View(course);
            }
            await _service.Update(id, course);
            return RedirectToAction(nameof(Index));
        }

        // GET: Courses/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var courseDetails = await _service.GetById(id);
            if (courseDetails == null)
            {
                return View("NotFound");
            }
            return View(courseDetails);
        }

        // POST: Courses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var courseDetails = await _service.GetById(id);
            if (courseDetails == null)
            {
                return View("NotFound");
            }

            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetCourseGroups(int id)
        {
            var courseGroups = await _service.GetCourseGroups(id);
            if (courseGroups == null)
            {
                return View("NotFound");
            }
            return View(courseGroups);
        }

        /*
        private bool CourseExists(int id)
        {
          return _context.Course.Any(e => e.Id == id);
        }*/
    }
}

9AspNetCoreWebAppMVC/9AspNetCoreWebAppMVC/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _9AspNetCoreWebAppMVC.Data;
using _9AspNetCoreWebAppMVC.Models;
using _9AspNetCoreWebAppMVC.Data.Services;

namespace _9AspNetCoreWebAppMVC.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IGropsService _service;

        public GroupsController(IGropsService service)
        {
            _service = service;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAll();
            return View(data);
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var groupDetails = await _service.GetById(id);
            if (groupDetails == null)
            {
                return View("NotFound");
            }
            return View(groupDetails);
        }

        // GET: Groups/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CourceId")] Group group)
        {
            if (!ModelState.IsValid)
            {
                return View(group);
            }
            await _service.Add(group);
            return RedirectToAction(nameof(Index));
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var groupDetails = await _service.GetById(id);
            if (groupDetails == null)
            {
                return View("NotFound");
            }
            return View(groupDetails);
        }

        // POST: Groups/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,CourceId")] Group group)
        {
            if (!ModelState.IsValid)
            {
                return View(group);
            }
            await _service.Update(id, group);
            return RedirectToAction(nameof(Index));
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var groupDetails = await _service.GetById(id);
            if (groupDetails == null)
            {
                return View("NotFound");
            }
            if (!_service.CheckGroup(id))
            {
                return View("GroupContsainsStudents");
            }
            return View(groupDetails);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var groupDetails = await _service.GetById(id);
            if (groupDetails == null)
            {
                return View("NotFound");
            }            
            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> GetGroupStudents(int id)
        {
            var groupStudents = await _service.GetGroupStudents(id);
            if (groupStudents == null)
            {
                return View("NotFound");
            }
            return View(groupStudents);
        }
        /*
        private bool GroupExists(int id)
        {
          return _context.Group.Any(e => e.Id == id);
        }*/
    }
}

9AspNetCoreWebAppMVC/9AspNetCoreWebAppMVC/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _9AspNetCoreWebAppMVC.Data;
using _9AspNetCoreWebAppMVC.Models;
using _9AspNetCoreWebAppMVC.Data.Services;

namespace _9AspNetCoreWebAppMVC.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IStudentsService _service;

        public StudentsController(IStudentsService service)
        {
            _service = service;
        }

        // GET: Students
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAll();
            return View(data);
        }

        // GET: Students/Create
        public async Task<IActionResult> Create()
        {
            return View();
        }

        // POST: Students/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GroupId,First_Name,Last_Name")] Student student)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            await _service.Add(student);
            return RedirectToAction(nameof(Index));
        }

                
        // GET: Students/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var studentDetails = await _service.GetById(id);
            if (studentDetails == null) 
            { 
                return View("NotFound"); 
            }
            return View(studentDetails);
        }

        
        // GET: Students/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var studentDetails = await _service.GetById(id);
            if (studentDetails == null)
            {
                return View("NotFound");
            }
            return View(studentDetails);
        }
        
        // POST: Students/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GroupId,First_Name,Last_Name")] Student student)
        {
            if (!ModelState.IsValid)
            {
                return View(student);
            }
            await _service.Update(id, student);
            return RedirectToAction(nameof(Index));
        }
        
        // GET: Students/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            var studentDetails = await _service.GetById(id);
            if (studentDetails == null)
            {
                return View("NotFound");
            }
            return View(studentDetails);
        }

        // POST: Students/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var studentDetails = await _service.GetById(id);
            if (studentDetails == null)
            {
                return View("NotFound");
            }

            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        /*
        private bool StudentExists(int id)
        {
          return _context.Student.Any(e => e.Id == id);
        }*/
    }
}

9AspNetCoreWebAppMVC/9AspNetCoreWebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _9AspNetCoreWebAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_9AspNetCoreWebAppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_9AspNetCoreWebAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Courses" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Groups" asp-action="Index">Groups</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - _9AspNetCoreWebAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>